# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  tasks:
  - fail:
      msg: required values not set
    when: cluster_id is not defined

# Add the created hosts to groups for configuration
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  vars_files:
  - vars.yml
  vars:
    master_hosts: "{{ groups['tag_openshift-master_' ~ cluster_id] }}"
    node_hosts: "{{ groups['tag_openshift-node_' ~ cluster_id] }}"
  tasks:
  - add_host:
      ansible_ssh_user: openshift
      ansible_sudo: yes
      name: "{{ item }}"
      groups: masters, etcd, nodes, cluster_hosts
      openshift_node_labels:
        region: master
        zone: "{{ hostvars[item].ec2_placement }}"
    with_items: groups['tag_openshift-demo-' ~ cluster_id ~ '-host-type_master']
  - add_host:
      ansible_ssh_user: openshift
      ansible_sudo: yes
      name: "{{ item }}"
      groups: nodes, cluster_hosts
      openshift_node_labels:
        region: "{{ 'infra' if  hostvars[item]['ec2_tag_openshift-demo-' ~ cluster_id ~ '-node-type'] == 'infrastructure' else 'demo' }}"
        zone: "{{ hostvars[item].ec2_placement }}"
    with_items: groups['tag_openshift-demo-' ~ cluster_id ~ '-host-type_node']

# Smoke projects
- name: Setting up smoke projects...
  hosts: masters[0]
  vars_files:
  - vars.yml
  tasks:
  - include: tasks/smoke_projects.yml
    when: run_smoke_tests | bool or run_only_smoke_tests | bool
