# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  tasks:
  - fail:
      msg: required values not set
    when: cluster_id is not defined

  - add_host:
      ansible_ssh_user: openshift
      ansible_sudo: yes
      name: "{{ groups['tag_openshift-demo-' ~ cluster_id ~ '-host-type_master'].0 }}"
      groups: project_master

# Smoke projects
- name: Setting up smoke projects...
  vars_files:
  - vars.yml
  hosts: project_master
  tasks:
  - include: tasks/smoke_projects.yml
    when: run_smoke_tests | bool or run_only_smoke_tests | bool
